// Generated by CoffeeScript 1.8.0
(function() {
  var $, Popup, ShareSNS,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $ = require('jquery');

  Popup = require('popup.js');

  ShareSNS = (function(_super) {
    "use strict";
    var _metaTags;

    __extends(ShareSNS, _super);

    _metaTags = document.getElementsByTagName('meta');

    ShareSNS.getMeta = function() {
      return _metaTags = document.getElementsByTagName('meta');
    };

    ShareSNS.prototype._defaults = {
      width: 640,
      height: 480,
      url: null,
      name: 'popup',
      type: ''
    };

    function ShareSNS(el, opts) {
      this.el = el;
      this.opts = $.extend({}, this._defaults, opts);
      this.$el = $(this.el);
      this.setParam();
      this.setURL();
      this.addEvent();
    }

    ShareSNS.prototype.setURL = function() {
      if (this.opts.type === 'twitter') {
        return this._setTwitterURL();
      } else if (this.opts.type === 'facebook') {
        return this._setFacebookURL();
      }
    };

    ShareSNS.prototype.addEvent = function() {
      return this.$el.on('click', (function(_this) {
        return function(ev) {
          ev.preventDefault();
          return _this.open();
        };
      })(this));
    };

    ShareSNS.prototype._setTwitterURL = function() {
      var maxLength, meta, metaProp, shareTitle, shareUrl, _i, _len;
      for (_i = 0, _len = _metaTags.length; _i < _len; _i++) {
        meta = _metaTags[_i];
        if (meta.getAttribute('property')) {
          metaProp = meta.getAttribute('property');
          if (metaProp === 'og:url') {
            shareUrl = meta.getAttribute('content');
          } else if (metaProp === 'og:title') {
            shareTitle = meta.getAttribute('content');
          }
        }
      }
      maxLength = 140 - (shareUrl.length + 1);
      if (shareTitle.length > maxLength) {
        shareTitle = "" + (shareTitle.substr(0, maxLength - 3)) + "...";
      }
      this._url = "https://twitter.com/share?url=" + (encodeURI(shareUrl)) + "&text=" + (encodeURI(shareTitle));
      return this;
    };

    ShareSNS.prototype._setFacebookURL = function() {
      var meta, metaProp, shareUrl, _i, _len;
      for (_i = 0, _len = _metaTags.length; _i < _len; _i++) {
        meta = _metaTags[_i];
        if (meta.getAttribute('property')) {
          metaProp = meta.getAttribute('property');
          if (metaProp === 'og:url') {
            shareUrl = meta.getAttribute('content');
          }
        }
      }
      this._url = "https://www.facebook.com/sharer.php?u=" + shareUrl;
      return this;
    };

    return ShareSNS;

  })(Popup);

  if (typeof define === 'function' && define.amd) {
    define(function() {
      return ShareSNS;
    });
  } else if (typeof module !== 'undefined' && module.exports) {
    module.exports = ShareSNS;
  } else {
    window.ShareSNS || (window.ShareSNS = ShareSNS);
  }

}).call(this);
